### PR TITLE
Explain that users should not need to set the endpoint

### PR DESCRIPTION
**Pull request by metadaddy**
Followup to #79 - clarify the purpose of the `endpoint`/`B2_ENDPOINT` config.

It looks like `docs/index.md` is automatically generated, and this is the source of truth.

### CODE REVIEW

**Comment by metadaddy** [comment]
Fine, I'll change the changelog...

**Comment by mlech-reef** [comment]
@metadaddy, you need to run `make docs` (after `make deps`) in order to regenerate `docs/`.

We may want to extend the functionality of `make docs-lint` that is being executed by the CI, to check if `docs/` are in sync with the source code.

**Comment by metadaddy** [comment]
Hi @mlech-reef - thanks! I tried to `make docs`, but it fails on the `pkger` step of the `build` target:

```
2024/08/29 09:19:02 exit status 1: main.go:14:2: import "github.com/hashicorp/terraform-plugin-docs/cmd/tfplugindocs" is a program, not an importable package
: here.Dir failed /Users/ppatterson/src/terraform-provider-b2/tools: /Users/ppatterson/src/terraform-provider-b2/tools
make: *** [build] Error 1
```

I've done a bit of googling, but I haven't been able to figure out the resolution.

Here's my environment:

```
% system_profiler SPSoftwareDataType
Software:

    System Software Overview:

      System Version: macOS 14.6 (23G80)
      Kernel Version: Darwin 23.6.0
      ...
% uname -a
Darwin MBP-W7FQ7Y97F0 23.6.0 Darwin Kernel Version 23.6.0: Fri Jul  5 17:56:41 PDT 2024; root:xnu-10063.141.1~2/RELEASE_ARM64_T6000 arm64
% go version
go version go1.22.2 darwin/arm64
% python --version
Python 3.10.14
% make --version
GNU Make 3.81
Copyright (C) 2006  Free Software Foundation, Inc.
This is free software; see the source for copying conditions.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE.

This program built for i386-apple-darwin11.3.0
```

**Comment by mlech-reef** [comment]
Yes, I have the same error with go1.22.2
```
make[1]: Leaving directory '.../terraform-provider-b2/python-bindings'
2024/08/30 17:21:01 exit status 1: main.go:14:2: import "github.com/hashicorp/terraform-plugin-docs/cmd/tfplugindocs" is a program, not an importable package
: here.Dir failed .../terraform-provider-b2/tools: .../terraform-provider-b2/tools
make: *** [GNUmakefile:49: build] Error 1
```

Continues Integrations uses go1.20 and python3.9 and these are the versions that I used to use.

Looks like moving to go1.22 will require more adjustments.

BR/ Maciek

**Comment by metadaddy** [comment]
Hi @mlech-reef - I grabbed your `upgrade-tools` PR (#84) and used it to `make docs`. This is all ready for review and merge. Thanks!

**Comment by mlech-reef** [comment]
Hi @metadaddy. Looks good.

**Review by mlech-reef — APPROVED** [review]

**Comment by metadaddy** [comment]
Hi @mlech-reef - I just fixed a conflict. Could you merge this before any more appear? Thanks!

**Pull request merged**
