### PR TITLE
Update staticx

### PR DESCRIPTION
**Pull request by vbaltrusaitis-reef**
staticx~=0.12.2 had a bug which caused the produced executable to always fail with error `tar_extract_all() failed: Symbolic link loop` on some systems.
Let's say the old version of staticx detects a library that needs to be included. If that path is actually a symbolic link to another file with the same name (but in a different directory), staticx includes `<libname> -> <libname>` link to the archive and the produced executable fails on runtime.

I didn't see a clear reference to this issue but the new version doesn't have this problem.

### CODE REVIEW

**Comment by kkalinowski-reef** [comment]
Does it sounds like this: https://github.com/JonathonReinhart/staticx/pull/225 ?

**Comment by vbaltrusaitis-reef** [comment]
Yep, this is exactly it.

**Comment by vbaltrusaitis-reef** [comment]
Rebased this branch on https://github.com/Backblaze/terraform-provider-b2/tree/ola/update-dep-libs-from-depbot

**Comment by vbaltrusaitis-reef** [comment]
The last commit fixes the CI failure. The reason for the failure was an interaction between `staticx`, `Pyinstaller` and `actions/setup-python@v2`. In short, `setup-python` action installs Python in a way which causes libraries in Pyinstaller archive to have `DT_RUNPATH` tags, which staticx does not support. The older version didn't fail in these situations, but that might result in binaries that actually depends on the libraries installed locally. More information:

* https://github.com/actions/setup-python/issues/325
* https://github.com/JonathonReinhart/staticx/issues/188
* https://staticx.readthedocs.io/en/latest/rpath.html

`deadsnakes` actions don't have this problem. Running `make build` in `python:3.9` container (which is done in `cd.yml`) also doesn't seem to have this problem, so changing the action in this one CI step should be enough.

**Pull request merged**
